// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationsUploadController from "./applications_upload_controller"
application.register("applications-upload", ApplicationsUploadController)
