// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ApplicationsUploadController from "./applications_upload_controller";
application.register("applications-upload", ApplicationsUploadController);

import Form__AutocompleteController from "./form/autocomplete_controller";
application.register("form--autocomplete", Form__AutocompleteController);

import Form__InvoiceAutocompleteController from "./form/invoice_autocomplete_controller";
application.register("form--invoice-autocomplete", Form__InvoiceAutocompleteController);

import Form__AddElementController from "./form/add_element_controller";
application.register("form--add-element", Form__AddElementController);

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)