development:
  adapter: redis
  url: <%= ENV.fetch("redis_url") { "redis://localhost:6379/1" } %>
  channel_prefix: eedirect_development
  # adapter: async

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("redis_url") { "redis://localhost:6379/1" } %>
  channel_prefix: eedirect_staging

production:
  adapter: redis
  url:  <%= ENV.fetch("redis_url") { "redis://localhost:6379/1" } %>
  channel_prefix: eedirect_production
